import json

# ==========================================
# 國中 1200 核心單字大圓滿 - 完整版
# ==========================================

part1_raw_data = [
    # 1A
    ("I", "我", "1A"), ("you", "你", "1A"), ("he", "他", "1A"), ("she", "她", "1A"), ("it", "它/牠", "1A"),
    ("we", "我們", "1A"), ("they", "他們", "1A"), ("me", "我(受格)", "1A"), ("him", "他(受格)", "1A"), ("her", "她(受格)", "1A"),
    ("us", "我們(受格)", "1A"), ("them", "他們(受格)", "1A"), ("my", "我的", "1A"), ("your", "你的", "1A"), ("his", "他的", "1A"),
    ("its", "它的", "1A"), ("our", "我們的", "1A"), ("their", "他們的", "1A"), ("mine", "我的(所有代名詞)", "1A"), ("yours", "你的(所有代名詞)", "1A"),
    ("this", "這個", "1A"), ("that", "那個", "1A"), ("these", "這些", "1A"), ("those", "那些", "1A"), ("am", "是", "1A"),
    ("is", "是", "1A"), ("are", "是", "1A"), ("was", "是(過去式)", "1A"), ("were", "是(過去式)", "1A"), ("be", "是/成為", "1A"),
    ("do", "做/助動詞", "1A"), ("does", "做/助動詞", "1A"), ("did", "做(過去式)", "1A"), ("have", "有", "1A"), ("has", "有", "1A"),
    ("had", "有(過去式)", "1A"), ("can", "能/會", "1A"), ("could", "能/會(過去式)", "1A"), ("will", "將要", "1A"), ("would", "將要(過去式)", "1A"),
    ("what", "什麼", "1A"), ("who", "誰", "1A"), ("where", "在哪裡", "1A"), ("when", "何時", "1A"), ("why", "為什麼", "1A"),
    ("how", "如何", "1A"), ("which", "哪一個", "1A"), ("whose", "誰的", "1A"), ("one", "一", "1A"), ("two", "二", "1A"),
    ("three", "三", "1A"), ("four", "四", "1A"), ("five", "五", "1A"), ("six", "六", "1A"), ("seven", "七", "1A"),
    ("eight", "八", "1A"), ("nine", "九", "1A"), ("ten", "十", "1A"), ("eleven", "十一", "1A"), ("twelve", "十二", "1A"),
    ("thirteen", "十三", "1A"), ("fourteen", "十四", "1A"), ("fifteen", "十五", "1A"), ("sixteen", "十六", "1A"), ("seventeen", "十七", "1A"),
    ("eighteen", "十八", "1A"), ("nineteen", "十九", "1A"), ("twenty", "二十", "1A"), ("thirty", "三十", "1A"), ("forty", "四十", "1A"),
    ("fifty", "五十", "1A"), ("sixty", "六十", "1A"), ("seventy", "七十", "1A"), ("eighty", "八十", "1A"), ("ninety", "九十", "1A"),
    ("hundred", "百", "1A"), ("thousand", "千", "1A"), ("million", "百萬", "1A"), ("red", "紅色", "1A"), ("blue", "藍色", "1A"),
    ("green", "綠色", "1A"), ("yellow", "黃色", "1A"), ("black", "黑色", "1A"), ("white", "白色", "1A"), ("gray", "灰色", "1A"),
    ("pink", "粉紅色", "1A"), ("purple", "紫色", "1A"), ("brown", "棕色", "1A"), ("orange", "橘色/橘子", "1A"), ("father", "父親", "1A"),
    ("mother", "母親", "1A"), ("brother", "兄弟", "1A"), ("sister", "姊妹", "1A"), ("grandfather", "祖父", "1A"), ("grandmother", "祖母", "1A"),
    ("uncle", "叔伯", "1A"), ("aunt", "姑姨", "1A"), ("son", "兒子", "1A"), ("daughter", "女兒", "1A"), ("cousin", "表/堂兄弟姊妹", "1A"),
    ("parent", "父母親", "1A"), ("husband", "丈夫", "1A"), ("wife", "妻子", "1A"), ("baby", "嬰兒", "1A"), ("teacher", "老師", "1A"),
    ("student", "學生", "1A"), ("friend", "朋友", "1A"), ("classmate", "同班同學", "1A"), ("boy", "男孩", "1A"), ("girl", "女孩", "1A"),
    ("man", "男人", "1A"), ("woman", "女人", "1A"), ("child", "小孩", "1A"), ("person", "人(單數)", "1A"), ("people", "人們(複數)", "1A"),
    ("school", "學校", "1A"), ("class", "班級/課", "1A"), ("book", "書", "1A"), ("pen", "原子筆", "1A"), ("pencil", "鉛筆", "1A"),
    ("eraser", "橡皮擦", "1A"), ("ruler", "尺", "1A"), ("bag", "袋子/書包", "1A"), ("desk", "書桌", "1A"), ("chair", "椅子", "1A"),
    ("paper", "紙", "1A"), ("box", "盒子", "1A"), ("picture", "圖片", "1A"), ("map", "地圖", "1A"), ("dog", "狗", "1A"),
    ("cat", "貓", "1A"), ("bird", "鳥", "1A"), ("fish", "魚", "1A"), ("pig", "豬", "1A"), ("cow", "母牛", "1A"),
    ("horse", "馬", "1A"), ("sheep", "綿羊", "1A"), ("chicken", "雞", "1A"), ("duck", "鴨", "1A"), ("monkey", "猴子", "1A"),
    ("elephant", "大象", "1A"), ("tiger", "老虎", "1A"), ("lion", "獅子", "1A"), ("bear", "熊", "1A"), ("big", "大的", "1A"),
    ("small", "小的", "1A"), ("tall", "高的", "1A"), ("short", "矮的/短的", "1A"), ("long", "長的", "1A"), ("old", "老的/舊的", "1A"),
    ("new", "新的", "1A"), ("young", "年輕的", "1A"), ("good", "好的", "1A"), ("bad", "壞的", "1A"), ("happy", "快樂的", "1A"),
    ("sad", "悲傷的", "1A"), ("angry", "生氣的", "1A"), ("tired", "疲倦的", "1A"), ("hungry", "飢餓的", "1A"), ("thirsty", "口渴的", "1A"),
    ("hot", "熱的", "1A"), ("cold", "冷的", "1A"), ("warm", "溫暖的", "1A"), ("cool", "涼爽的", "1A"), ("eat", "吃", "1A"),
    ("drink", "喝", "1A"), ("play", "玩", "1A"), ("run", "跑", "1A"), ("jump", "跳躍", "1A"), ("swim", "游泳", "1A"),
    ("sit", "坐", "1A"), ("stand", "站立", "1A"), ("read", "閱讀", "1A"), ("write", "寫", "1A"), ("listen", "聽", "1A"),
    ("speak", "說(語言)", "1A"), ("talk", "談話", "1A"), ("say", "說", "1A"), ("tell", "告訴", "1A"), ("look", "看", "1A"),
    ("see", "看見", "1A"), ("watch", "觀看", "1A"), ("sleep", "睡覺", "1A"), ("wake", "醒來", "1A"), ("open", "打開", "1A"),
    ("close", "關閉", "1A"), ("come", "來", "1A"), ("go", "去", "1A"), ("apple", "蘋果", "1A"), ("banana", "香蕉", "1A"),
    ("water", "水", "1A"), ("milk", "牛奶", "1A"), ("tea", "茶", "1A"), ("juice", "果汁", "1A"), ("bread", "麵包", "1A"),
    ("rice", "米飯", "1A"), ("egg", "蛋", "1A"), ("monday", "星期一", "1A"), ("tuesday", "星期二", "1A"), ("wednesday", "星期三", "1A"),
    ("thursday", "星期四", "1A"), ("friday", "星期五", "1A"), ("saturday", "星期六", "1A"), ("sunday", "星期日", "1A"), ("today", "今天", "1A"),
    ("tomorrow", "明天", "1A"), ("yesterday", "昨天", "1A"), ("very", "非常", "1A"), ("too", "太/也", "1A"), ("much", "多(不可數)", "1A"),
    ("many", "多(可數)", "1A"), ("here", "這裡", "1A"), ("there", "那裡", "1A"), ("now", "現在", "1A"), ("then", "那時/然後", "1A"),
    ("in", "在...裡面", "1A"), ("on", "在...上面", "1A"), ("at", "在(特定地點/時間)", "1A"), ("under", "在...下面", "1A"), ("up", "向上", "1A"),
    ("down", "向下", "1A"), ("to", "往/向", "1A"), ("for", "為了/給", "1A"), ("with", "和/用", "1A"), ("about", "關於", "1A"),

    # 1B
    ("january", "一月", "1B"), ("february", "二月", "1B"), ("march", "三月", "1B"), ("april", "四月", "1B"), ("may", "五月", "1B"),
    ("june", "六月", "1B"), ("july", "七月", "1B"), ("august", "八月", "1B"), ("september", "九月", "1B"), ("october", "十月", "1B"),
    ("november", "十一月", "1B"), ("december", "十二月", "1B"), ("month", "月份", "1B"), ("year", "年", "1B"), ("season", "季節", "1B"),
    ("spring", "春天", "1B"), ("summer", "夏天", "1B"), ("fall", "秋天", "1B"), ("autumn", "秋天", "1B"), ("winter", "冬天", "1B"),
    ("weather", "天氣", "1B"), ("sun", "太陽", "1B"), ("moon", "月亮", "1B"), ("star", "星星", "1B"), ("rain", "雨", "1B"),
    ("snow", "雪", "1B"), ("wind", "風", "1B"), ("cloud", "雲", "1B"), ("sky", "天空", "1B"), ("sunny", "晴朗的", "1B"),
    ("rainy", "下雨的", "1B"), ("cloudy", "多雲的", "1B"), ("windy", "風大的", "1B"), ("snowy", "下雪的", "1B"), ("head", "頭", "1B"),
    ("hair", "頭髮", "1B"), ("face", "臉", "1B"), ("eye", "眼睛", "1B"), ("ear", "耳朵", "1B"), ("nose", "鼻子", "1B"),
    ("mouth", "嘴巴", "1B"), ("tooth", "牙齒", "1B"), ("arm", "手臂", "1B"), ("hand", "手", "1B"), ("leg", "腿", "1B"),
    ("foot", "腳", "1B"), ("body", "身體", "1B"), ("home", "家", "1B"), ("house", "房子", "1B"), ("room", "房間", "1B"),
    ("living room", "客廳", "1B"), ("bedroom", "臥室", "1B"), ("bathroom", "浴室", "1B"), ("kitchen", "廚房", "1B"), ("door", "門", "1B"),
    ("window", "窗戶", "1B"), ("bed", "床", "1B"), ("table", "桌子(餐桌)", "1B"), ("sofa", "沙發", "1B"), ("lamp", "燈", "1B"),
    ("fan", "電風扇", "1B"), ("park", "公園", "1B"), ("zoo", "動物園", "1B"), ("hospital", "醫院", "1B"), ("bank", "銀行", "1B"),
    ("post office", "郵局", "1B"), ("library", "圖書館", "1B"), ("store", "商店", "1B"), ("shop", "商店", "1B"), ("market", "市場", "1B"),
    ("restaurant", "餐廳", "1B"), ("supermarket", "超市", "1B"), ("museum", "博物館", "1B"), ("theater", "戲院", "1B"), ("factory", "工廠", "1B"),
    ("office", "辦公室", "1B"), ("farm", "農場", "1B"), ("car", "汽車", "1B"), ("bus", "公車", "1B"), ("train", "火車", "1B"),
    ("bike", "腳踏車", "1B"), ("bicycle", "腳踏車", "1B"), ("boat", "小船", "1B"), ("ship", "大船", "1B"), ("plane", "飛機", "1B"),
    ("airplane", "飛機", "1B"), ("taxi", "計程車", "1B"), ("motorcycle", "機車", "1B"), ("truck", "卡車", "1B"), ("doctor", "醫生", "1B"),
    ("nurse", "護士", "1B"), ("driver", "司機", "1B"), ("cook", "廚師", "1B"), ("worker", "工人", "1B"), ("police", "警察", "1B"),
    ("singer", "歌手", "1B"), ("dancer", "舞者", "1B"), ("farmer", "農夫", "1B"), ("actor", "男演員", "1B"), ("actress", "女演員", "1B"),
    ("writer", "作家", "1B"), ("reporter", "記者", "1B"), ("clerk", "店員", "1B"), ("businessman", "商人", "1B"), ("always", "總是", "1B"),
    ("usually", "通常", "1B"), ("often", "經常", "1B"), ("sometimes", "有時", "1B"), ("never", "從不", "1B"), ("early", "早的", "1B"),
    ("late", "晚的", "1B"), ("fast", "快", "1B"), ("slow", "慢", "1B"), ("quickly", "快速地", "1B"), ("slowly", "緩慢地", "1B"),
    ("next to", "在...旁邊", "1B"), ("near", "在...附近", "1B"), ("behind", "在...後面", "1B"), ("front", "前面", "1B"), ("between", "在...之間", "1B"),
    ("inside", "在裡面", "1B"), ("outside", "在外面", "1B"), ("left", "左邊", "1B"), ("right", "右邊", "1B"), ("top", "頂部", "1B"),
    ("bottom", "底部", "1B"), ("breakfast", "早餐", "1B"), ("lunch", "午餐", "1B"), ("dinner", "晚餐", "1B"), ("meal", "餐", "1B"),
    ("cake", "蛋糕", "1B"), ("cookie", "餅乾", "1B"), ("candy", "糖果", "1B"), ("ice cream", "冰淇淋", "1B"), ("fruit", "水果", "1B"),
    ("vegetable", "蔬菜", "1B"), ("meat", "肉", "1B"), ("beef", "牛肉", "1B"), ("pork", "豬肉", "1B"), ("fish", "魚肉", "1B"),
    ("soup", "湯", "1B"), ("salad", "沙拉", "1B"), ("sandwich", "三明治", "1B"), ("hamburger", "漢堡", "1B"), ("pizza", "披薩", "1B"),
    ("noodle", "麵條", "1B"), ("french fries", "薯條", "1B"), ("wash", "洗", "1B"), ("clean", "清理", "1B"), ("help", "幫助", "1B"),
    ("work", "工作", "1B"), ("study", "學習", "1B"), ("learn", "學習", "1B"), ("ask", "詢問", "1B"), ("answer", "回答", "1B"),
    ("buy", "買", "1B"), ("sell", "賣", "1B"), ("pay", "付款", "1B"), ("spend", "花費", "1B"), ("cost", "價值", "1B"),
    ("bring", "帶來", "1B"), ("take", "拿走", "1B"), ("get", "得到", "1B"), ("give", "給", "1B"), ("make", "製造", "1B"),
    ("build", "建立", "1B"), ("fix", "修理", "1B"), ("use", "使用", "1B"), ("wear", "穿戴", "1B"), ("beautiful", "美麗的", "1B"),
    ("ugly", "醜陋的", "1B"), ("cute", "可愛的", "1B"), ("smart", "聰明的", "1B"), ("stupid", "愚笨的", "1B"), ("lazy", "懶惰的", "1B"),
    ("hard-working", "勤勞的", "1B"), ("rich", "富有的", "1B"), ("poor", "貧窮的", "1B"), ("heavy", "重的", "1B"), ("light", "輕的", "1B"),
    ("thick", "厚的", "1B"), ("thin", "薄的/瘦的", "1B"), ("fat", "胖的", "1B"), ("fine", "好的", "1B"), ("great", "棒的", "1B"),
    ("excellent", "極好的", "1B"), ("terrible", "可怕的", "1B"), ("shirt", "襯衫", "1B"), ("t-shirt", "T恤", "1B"), ("coat", "外套", "1B"),
    ("jacket", "夾克", "1B"), ("pants", "褲子", "1B"), ("jeans", "牛仔褲", "1B"), ("skirt", "裙子", "1B"), ("dress", "洋裝", "1B"),
    ("shoe", "鞋子", "1B"), ("sock", "襪子", "1B"), ("hat", "帽子", "1B"), ("cap", "棒球帽", "1B"), ("glasses", "眼鏡", "1B"),
    ("umbrella", "雨傘", "1B"), ("sport", "運動", "1B"), ("baseball", "棒球", "1B"), ("basketball", "籃球", "1B"), ("soccer", "足球", "1B"),
    ("tennis", "網球", "1B"), ("badminton", "羽毛球", "1B"), ("ping-pong", "桌球", "1B"), ("dodgeball", "躲避球", "1B"), ("frisbee", "飛盤", "1B"),
    ("jog", "慢跑", "1B"), ("hike", "健行", "1B"), ("camp", "露營", "1B"), ("sing", "唱歌", "1B"), ("dance", "跳舞", "1B"),
    ("draw", "畫畫", "1B"), ("paint", "繪畫/油漆", "1B"), ("music", "音樂", "1B"), ("song", "歌曲", "1B"), ("piano", "鋼琴", "1B"),
    ("guitar", "吉他", "1B"), ("violin", "小提琴", "1B"), ("money", "金錢", "1B"), ("dollar", "元", "1B"), ("cent", "分", "1B"),
    ("cash", "現金", "1B"), ("card", "卡片", "1B"), ("ticket", "票", "1B"), ("wallet", "錢包", "1B"),

    # 2A
    ("health", "健康", "2A"), ("sick", "生病的", "2A"), ("ill", "生病的", "2A"), ("fever", "發燒", "2A"), ("headache", "頭痛", "2A"),
    ("toothache", "牙痛", "2A"), ("stomachache", "胃痛", "2A"), ("sore throat", "喉嚨痛", "2A"), ("cough", "咳嗽", "2A"), ("medicine", "藥", "2A"),
    ("pill", "藥丸", "2A"), ("clinic", "診所", "2A"), ("patient", "病人", "2A"), ("healthy", "健康的", "2A"), ("weak", "虛弱的", "2A"),
    ("strong", "強壯的", "2A"), ("holiday", "假日", "2A"), ("festival", "節慶", "2A"), ("party", "派對", "2A"), ("gift", "禮物", "2A"),
    ("present", "禮物", "2A"), ("celebrate", "慶祝", "2A"), ("invite", "邀請", "2A"), ("join", "參加", "2A"), ("halloween", "萬聖節", "2A"),
    ("thanksgiving", "感恩節", "2A"), ("christmas", "聖誕節", "2A"), ("history", "歷史", "2A"), ("science", "科學", "2A"), ("math", "數學", "2A"),
    ("english", "英文", "2A"), ("art", "美術", "2A"), ("pe", "體育", "2A"), ("geography", "地理", "2A"), ("biology", "生物", "2A"),
    ("subject", "科目", "2A"), ("lesson", "課程", "2A"), ("grade", "成績/年級", "2A"), ("test", "考試", "2A"), ("exam", "測驗", "2A"),
    ("quiz", "小考", "2A"), ("homework", "作業", "2A"), ("fail", "不及格", "2A"), ("pass", "通過", "2A"), ("internet", "網路", "2A"),
    ("email", "電子郵件", "2A"), ("website", "網站", "2A"), ("online", "線上的", "2A"), ("offline", "離線的", "2A"), ("screen", "螢幕", "2A"),
    ("keyboard", "鍵盤", "2A"), ("mouse", "滑鼠", "2A"), ("click", "點擊", "2A"), ("type", "打字", "2A"), ("message", "訊息", "2A"),
    ("app", "應用程式", "2A"), ("cellphone", "手機", "2A"), ("smartphone", "智慧型手機", "2A"), ("computer", "電腦", "2A"), ("radio", "收音機", "2A"),
    ("television", "電視", "2A"), ("video", "影片", "2A"), ("camera", "相機", "2A"), ("photo", "相片", "2A"), ("nature", "自然", "2A"),
    ("earth", "地球", "2A"), ("world", "世界", "2A"), ("ocean", "海洋", "2A"), ("sea", "海", "2A"), ("island", "島嶼", "2A"),
    ("forest", "森林", "2A"), ("mountain", "山", "2A"), ("tree", "樹木", "2A"), ("flower", "花", "2A"), ("grass", "草", "2A"),
    ("leaf", "葉子", "2A"), ("river", "河流", "2A"), ("lake", "湖泊", "2A"), ("pond", "池塘", "2A"), ("beach", "海灘", "2A"),
    ("sand", "沙", "2A"), ("rock", "岩石", "2A"), ("stone", "石頭", "2A"), ("air", "空氣", "2A"), ("recycle", "回收", "2A"),
    ("plastic", "塑膠", "2A"), ("metal", "金屬", "2A"), ("glass", "玻璃", "2A"), ("pollution", "污染", "2A"), ("trash", "垃圾", "2A"),
    ("garbage", "垃圾", "2A"), ("rubbish", "垃圾", "2A"), ("waste", "廢物/浪費", "2A"), ("dirty", "髒的", "2A"), ("save", "拯救/省", "2A"),
    ("protect", "保護", "2A"), ("environment", "環境", "2A"), ("safe", "安全的", "2A"), ("dangerous", "危險的", "2A"), ("trip", "旅行", "2A"),
    ("travel", "旅遊", "2A"), ("tour", "旅行團", "2A"), ("vacation", "假期", "2A"), ("passport", "護照", "2A"), ("luggage", "行李", "2A"),
    ("airport", "機場", "2A"), ("station", "車站", "2A"), ("hotel", "旅館", "2A"), ("flight", "班機", "2A"), ("guide", "導遊", "2A"),
    ("foreign", "外國的", "2A"), ("country", "國家", "2A"), ("city", "城市", "2A"), ("town", "城鎮", "2A"), ("village", "村莊", "2A"),
    ("capital", "首都", "2A"), ("future", "未來", "2A"), ("plan", "計畫", "2A"), ("dream", "夢想", "2A"), ("goal", "目標", "2A"),
    ("career", "職業", "2A"), ("business", "生意", "2A"), ("engineer", "工程師", "2A"), ("pilot", "飛行員", "2A"), ("lawyer", "律師", "2A"),
    ("boss", "老闆", "2A"), ("manager", "經理", "2A"), ("secretary", "秘書", "2A"), ("soldier", "士兵", "2A"), ("scientist", "科學家", "2A"),
    ("success", "成功", "2A"), ("succeed", "成功(動詞)", "2A"), ("try", "嘗試", "2A"), ("practice", "練習", "2A"), ("exercise", "運動/練習", "2A"),
    ("prepare", "準備", "2A"), ("review", "複習", "2A"), ("remember", "記得", "2A"), ("forget", "忘記", "2A"), ("believe", "相信", "2A"),
    ("decide", "決定", "2A"), ("understand", "了解", "2A"), ("guess", "猜測", "2A"), ("hope", "希望", "2A"), ("wish", "願望", "2A"),
    ("agree", "同意", "2A"), ("disagree", "不同意", "2A"), ("more", "更多", "2A"), ("less", "較少", "2A"), ("better", "更好", "2A"),
    ("worse", "更糟", "2A"), ("most", "最多", "2A"), ("least", "最少", "2A"), ("best", "最好", "2A"), ("worst", "最糟", "2A"),
    ("enough", "足夠的", "2A"), ("almost", "幾乎", "2A"), ("already", "已經", "2A"), ("maybe", "也許", "2A"), ("perhaps", "或許", "2A"),
    ("really", "真地", "2A"), ("exactly", "確切地", "2A"), ("ant", "螞蟻", "2A"), ("bee", "蜜蜂", "2A"), ("bug", "蟲子", "2A"),
    ("butterfly", "蝴蝶", "2A"), ("insect", "昆蟲", "2A"), ("spider", "蜘蛛", "2A"), ("frog", "青蛙", "2A"), ("turtle", "烏龜", "2A"),
    ("snake", "蛇", "2A"), ("rat", "大老鼠", "2A"), ("mouse", "滑鼠/老鼠", "2A"), ("hammer", "鐵鎚", "2A"), ("nail", "釘子/指甲", "2A"),
    ("tool", "工具", "2A"), ("machine", "機器", "2A"), ("robot", "機器人", "2A"), ("shape", "形狀", "2A"), ("circle", "圓形", "2A"),
    ("square", "正方形", "2A"), ("triangle", "三角形", "2A"), ("line", "線", "2A")
]

part2_raw_data = [
    # 2B
    ("space", "太空/空間", "2B"), ("universe", "宇宙", "2B"), ("planet", "行星", "2B"), ("ground", "地面", "2B"), ("soil", "土壤", "2B"), ("dirt", "泥土", "2B"),
    ("mud", "泥巴", "2B"), ("sand", "沙子", "2B"), ("rock", "岩石", "2B"), ("stone", "石頭", "2B"), ("gold", "黃金", "2B"), ("silver", "白銀", "2B"),
    ("iron", "鐵", "2B"), ("wood", "木頭", "2B"), ("board", "木板", "2B"), ("branch", "樹枝", "2B"), ("leaf", "葉子", "2B"), ("root", "根部", "2B"),
    ("plant", "植物/種植", "2B"), ("seed", "種子", "2B"), ("crop", "農作物", "2B"), ("corn", "玉米", "2B"), ("bean", "豆子", "2B"), ("nut", "堅果", "2B"),
    ("wave", "波浪", "2B"), ("coast", "海岸", "2B"), ("shore", "岸邊", "2B"), ("beach", "海灘", "2B"), ("pool", "池子", "2B"), ("drop", "滴/掉落", "2B"),
    ("steam", "蒸氣", "2B"), ("ice", "冰", "2B"), ("fog", "霧", "2B"), ("storm", "暴風雨", "2B"), ("thunder", "雷", "2B"), ("lightning", "閃電", "2B"),
    ("rainbow", "彩虹", "2B"), ("breeze", "微風", "2B"), ("shadow", "影子", "2B"), ("tool", "工具", "2B"), ("hammer", "鐵鎚", "2B"), ("nail", "釘子/指甲", "2B"),
    ("saw", "鋸子/看見(過)", "2B"), ("scissors", "剪刀", "2B"), ("knife", "刀子", "2B"), ("fork", "叉子", "2B"), ("spoon", "湯匙", "2B"), ("plate", "盤子", "2B"),
    ("bowl", "碗", "2B"), ("cup", "杯子", "2B"), ("glass", "玻璃/玻璃杯", "2B"), ("dish", "菜餚/盤子", "2B"), ("pan", "平底鍋", "2B"), ("pot", "鍋子", "2B"),
    ("basket", "籃子", "2B"), ("bucket", "水桶", "2B"), ("bottle", "瓶子", "2B"), ("box", "盒子", "2B"), ("pack", "包裹/打包", "2B"), ("pocket", "口袋", "2B"),
    ("purse", "女用錢包", "2B"), ("wallet", "皮夾", "2B"), ("umbrella", "雨傘", "2B"), ("towel", "毛巾", "2B"), ("soap", "肥皂", "2B"), ("brush", "刷子", "2B"),
    ("comb", "梳子", "2B"), ("mirror", "鏡子", "2B"), ("rope", "繩子", "2B"), ("string", "細繩", "2B"), ("wire", "電線", "2B"), ("lock", "鎖", "2B"),
    ("key", "鑰匙", "2B"), ("ring", "戒指/環", "2B"), ("bell", "鈴鐺", "2B"), ("lamp", "燈", "2B"), ("light", "光線/燈", "2B"), ("candle", "蠟燭", "2B"),
    ("match", "火柴/比賽", "2B"), ("fire", "火", "2B"), ("smoke", "煙", "2B"), ("oil", "油", "2B"), ("gas", "瓦斯/氣體", "2B"), ("pipe", "管子", "2B"),
    ("place", "地方", "2B"), ("spot", "斑點/地點", "2B"), ("point", "點/得分", "2B"), ("area", "區域", "2B"), ("center", "中心", "2B"), ("middle", "中間", "2B"),
    ("side", "旁邊/側面", "2B"), ("edge", "邊緣", "2B"), ("corner", "角落", "2B"), ("front", "前面", "2B"), ("back", "後面/背部", "2B"), ("top", "頂端", "2B"),
    ("bottom", "底部", "2B"), ("east", "東方", "2B"), ("west", "西方", "2B"), ("south", "南方", "2B"), ("north", "北方", "2B"), ("straight", "直的", "2B"),
    ("forward", "向前", "2B"), ("backward", "向後", "2B"), ("cross", "十字架/越過", "2B"), ("past", "過去/經過", "2B"), ("along", "沿著", "2B"), ("block", "街區/阻擋", "2B"),
    ("street", "街道", "2B"), ("road", "道路", "2B"), ("path", "小徑", "2B"), ("way", "方法/道路", "2B"), ("highway", "公路", "2B"), ("bridge", "橋", "2B"),
    ("tunnel", "隧道", "2B"), ("temple", "寺廟", "2B"), ("church", "教堂", "2B"), ("castle", "城堡", "2B"), ("tower", "塔", "2B"), ("building", "建築物", "2B"),
    ("apartment", "公寓", "2B"), ("factory", "工廠", "2B"), ("company", "公司", "2B"), ("office", "辦公室", "2B"), ("mall", "購物中心", "2B"), ("market", "市場", "2B"),
    
    # 3A
    ("life", "生活/生命", "3A"), ("death", "死亡", "3A"), ("birth", "出生", "3A"), ("age", "年齡", "3A"), ("health", "健康", "3A"), ("disease", "疾病", "3A"),
    ("pain", "痛苦", "3A"), ("hurt", "傷害", "3A"), ("wound", "傷口", "3A"), ("mind", "心智/介意", "3A"), ("thought", "想法", "3A"), ("idea", "點子", "3A"),
    ("plan", "計畫", "3A"), ("dream", "夢想", "3A"), ("goal", "目標", "3A"), ("purpose", "目的", "3A"), ("reason", "理由", "3A"), ("result", "結果", "3A"),
    ("cause", "原因/造成", "3A"), ("effect", "效果/影響", "3A"), ("power", "力量/權力", "3A"), ("force", "強迫/力量", "3A"), ("energy", "活力/能源", "3A"), ("strength", "力量/優點", "3A"),
    ("weakness", "弱點", "3A"), ("peace", "和平", "3A"), ("war", "戰爭", "3A"), ("fight", "打架/戰鬥", "3A"), ("danger", "危險", "3A"), ("safety", "安全", "3A"),
    ("risk", "風險", "3A"), ("chance", "機會", "3A"), ("opportunity", "機會", "3A"), ("luck", "運氣", "3A"), ("success", "成功", "3A"), ("failure", "失敗", "3A"),
    ("mistake", "錯誤", "3A"), ("truth", "真相", "3A"), ("lie", "謊言/說謊", "3A"), ("secret", "秘密", "3A"), ("trick", "把戲/惡作劇", "3A"), ("joke", "笑話", "3A"),
    ("joy", "喜悅", "3A"), ("sorrow", "悲傷", "3A"), ("anger", "憤怒", "3A"), ("fear", "恐懼", "3A"), ("courage", "勇氣", "3A"), ("hope", "希望", "3A"),
    ("pity", "同情/遺憾", "3A"), ("honor", "榮譽", "3A"), ("pride", "驕傲", "3A"), ("shame", "羞恥", "3A"), ("culture", "文化", "3A"), ("custom", "習俗", "3A"),
    ("tradition", "傳統", "3A"), ("habit", "習慣", "3A"), ("rule", "規則", "3A"), ("law", "法律", "3A"), ("order", "秩序/點餐", "3A"), ("society", "社會", "3A"),
    ("community", "社區", "3A"), ("nation", "國家", "3A"), ("country", "國家/鄉村", "3A"), ("state", "州/狀態", "3A"), ("city", "城市", "3A"), ("town", "城鎮", "3A"),
    ("village", "村莊", "3A"), ("capital", "首都", "3A"), ("citizen", "公民", "3A"), ("public", "公眾的", "3A"), ("private", "私人的", "3A"), ("leader", "領導者", "3A"),
    ("president", "總統/校長", "3A"), ("king", "國王", "3A"), ("queen", "皇后", "3A"), ("prince", "王子", "3A"), ("princess", "公主", "3A"), ("boss", "老闆", "3A"),
    ("manager", "經理", "3A"), ("clerk", "店員/職員", "3A"), ("worker", "工人", "3A"), ("employee", "員工", "3A"), ("member", "成員", "3A"), ("partner", "夥伴", "3A"),
    ("group", "團體", "3A"), ("team", "隊伍", "3A"), ("club", "俱樂部", "3A"), ("level", "等級", "3A"), ("grade", "成績/年級", "3A"), ("score", "分數", "3A"),
    ("record", "紀錄", "3A"), ("history", "歷史", "3A"), ("science", "科學", "3A"), ("language", "語言", "3A"), ("prize", "獎品", "3A"), ("reward", "報酬/獎賞", "3A"),
    ("gift", "禮物/天賦", "3A"), ("think", "想", "3A"), ("guess", "猜測", "3A"), ("wonder", "想知道", "3A"), ("believe", "相信", "3A"), ("doubt", "懷疑", "3A"),
    ("trust", "信任", "3A"), ("expect", "期待", "3A"), ("remember", "記得", "3A"), ("forget", "忘記", "3A"), ("remind", "提醒", "3A"), ("understand", "理解", "3A"),
    ("notice", "注意到", "3A"), ("realize", "了解到", "3A"), ("discover", "發現", "3A"), ("invent", "發明", "3A"), ("create", "創造", "3A"), ("imagine", "想像", "3A"),
    ("decide", "決定", "3A"), ("choose", "選擇", "3A"), ("select", "挑選", "3A"), ("agree", "同意", "3A"), ("disagree", "不同意", "3A"), ("accept", "接受", "3A"),
    ("refuse", "拒絕", "3A"), ("deny", "否認", "3A"), ("admit", "承認", "3A"), ("complain", "抱怨", "3A"), ("promise", "承諾", "3A"), ("forgive", "原諒", "3A"),
    ("apologize", "道歉", "3A"), ("welcome", "歡迎", "3A"), ("greet", "打招呼", "3A"), ("invite", "邀請", "3A"), ("visit", "拜訪", "3A"), ("cry", "哭泣", "3A"),
    ("shout", "大喊", "3A"), ("yell", "吼叫", "3A"), ("scream", "尖叫", "3A"), ("whisper", "耳語", "3A"), ("speak", "說(語言)", "3A"), ("talk", "談話", "3A"),
    ("say", "說", "3A"), ("tell", "告訴", "3A"), ("answer", "回答", "3A"), ("reply", "回覆", "3A"), ("question", "問題/質疑", "3A"), ("explain", "解釋", "3A"),
    ("describe", "描述", "3A"), ("spell", "拼字", "3A"), ("mean", "意指", "3A"), ("translate", "翻譯", "3A"), ("act", "行動/表演", "3A"), ("build", "建造", "3A"),
    ("construct", "建設", "3A"), ("fix", "修理", "3A"), ("repair", "修復", "3A"), ("mend", "修補", "3A"), ("break", "打破", "3A"), ("crack", "裂開", "3A"),

    # 3B
    ("tear", "撕裂/眼淚", "3B"), ("cut", "切/剪", "3B"), ("divide", "分開", "3B"), ("share", "分享", "3B"), ("join", "加入", "3B"), ("connect", "連接", "3B"),
    ("tie", "綁/平手", "3B"), ("bind", "綑綁", "3B"), ("hold", "握住/舉辦", "3B"), ("keep", "保持", "3B"), ("save", "拯救/存錢", "3B"), ("spend", "花費", "3B"),
    ("waste", "浪費", "3B"), ("use", "使用", "3B"), ("cost", "花費(金錢)", "3B"), ("pay", "付錢", "3B"), ("buy", "買", "3B"), ("sell", "賣", "3B"),
    ("trade", "貿易/交易", "3B"), ("rent", "租用", "3B"), ("borrow", "借入", "3B"), ("lend", "借出", "3B"), ("earn", "賺取", "3B"), ("win", "贏", "3B"),
    ("lose", "失去/輸", "3B"), ("beat", "擊敗/打", "3B"), ("fail", "失敗", "3B"), ("succeed", "成功(動詞)", "3B"), ("finish", "完成", "3B"), ("complete", "完成/完整的", "3B"),
    ("end", "結束", "3B"), ("start", "開始", "3B"), ("begin", "開始", "3B"), ("open", "打開", "3B"), ("close", "關閉", "3B"), ("shut", "關上", "3B"),
    ("lock", "上鎖", "3B"), ("unlock", "解鎖", "3B"), ("cover", "覆蓋", "3B"), ("hide", "隱藏", "3B"), ("show", "展示", "3B"), ("display", "陳列/顯示", "3B"),
    ("appear", "出現/似乎", "3B"), ("disappear", "消失", "3B"), ("seem", "似乎", "3B"), ("look", "看起來/看", "3B"), ("sound", "聽起來/聲音", "3B"), ("smell", "聞起來/氣味", "3B"),
    ("taste", "嚐起來/味道", "3B"), ("feel", "感覺", "3B"), ("touch", "觸摸", "3B"), ("hit", "打擊", "3B"), ("strike", "打擊/罷工", "3B"), ("kick", "踢", "3B"),
    ("push", "推", "3B"), ("pull", "拉", "3B"), ("throw", "丟", "3B"), ("catch", "接住/抓", "3B"), ("fall", "掉落/秋天", "3B"), ("slip", "滑倒", "3B"),
    ("slide", "滑動", "3B"), ("roll", "滾動", "3B"), ("turn", "轉向", "3B"), ("spin", "旋轉", "3B"), ("lift", "舉起/電梯", "3B"), ("raise", "舉起/募款", "3B"),
    ("rise", "上升", "3B"), ("grow", "成長/種植", "3B"), ("change", "改變/零錢", "3B"), ("become", "變成", "3B"), ("happen", "發生", "3B"), ("occur", "發生", "3B"),
    ("belong", "屬於", "3B"), ("matter", "要緊/事情", "3B"), ("care", "在乎/照顧", "3B"), ("rich", "富有的", "3B"), ("poor", "貧窮的", "3B"), ("cheap", "便宜的", "3B"),
    ("expensive", "昂貴的", "3B"), ("dear", "親愛的/昂貴的", "3B"), ("free", "自由的/免費的", "3B"), ("busy", "忙碌的", "3B"), ("lazy", "懶惰的", "3B"), ("hard", "困難的/硬的", "3B"),
    ("easy", "簡單的", "3B"), ("simple", "簡單的", "3B"), ("complex", "複雜的", "3B"), ("clear", "清楚的", "3B"), ("bright", "明亮的", "3B"), ("dark", "黑暗的", "3B"),
    ("dim", "昏暗的", "3B"), ("light", "輕的/光線", "3B"), ("heavy", "重的", "3B"), ("loud", "大聲的", "3B"), ("quiet", "安靜的", "3B"), ("silent", "沉默的", "3B"),
    ("still", "靜止的/仍然", "3B"), ("soft", "柔軟的", "3B"), ("rough", "粗糙的", "3B"), ("smooth", "平滑的", "3B"), ("sharp", "尖銳的", "3B"), ("dull", "遲鈍的/無聊的", "3B"),
    ("thick", "厚的", "3B"), ("thin", "薄的/瘦的", "3B"), ("wide", "寬的", "3B"), ("narrow", "窄的", "3B"), ("deep", "深的", "3B"), ("shallow", "淺的", "3B"),
    ("flat", "平的", "3B"), ("round", "圓形的", "3B"), ("square", "正方形的", "3B"), ("straight", "直的", "3B"), ("bent", "彎曲的", "3B"), ("full", "滿的", "3B"),
    ("empty", "空的", "3B"), ("blank", "空白的", "3B"), ("clean", "乾淨的", "3B"), ("dirty", "髒的", "3B"), ("neat", "整潔的", "3B"), ("messy", "凌亂的", "3B"),
    ("pure", "純潔的", "3B"), ("fresh", "新鮮的", "3B"), ("safe", "安全的", "3B"), ("dangerous", "危險的", "3B"), ("fast", "快的", "3B"), ("quick", "迅速的", "3B"),
    ("rapid", "快速的", "3B"), ("slow", "慢的", "3B"), ("early", "早的", "3B"), ("late", "晚的/遲的", "3B"), ("true", "真實的", "3B"), ("false", "錯誤的", "3B"),
    ("real", "真實的", "3B"), ("fake", "假的", "3B"), ("right", "右邊/正確的", "3B"), ("wrong", "錯誤的", "3B"), ("correct", "正確的", "3B"), ("fair", "公平的", "3B"),
    ("equal", "平等的", "3B"), ("strange", "奇怪的", "3B"), ("odd", "奇數的/奇怪的", "3B"), ("usual", "尋常的", "3B"), ("normal", "正常的", "3B"), ("common", "常見的", "3B"),
    ("rare", "罕見的", "3B"), ("special", "特別的", "3B"), ("general", "一般的", "3B"), ("single", "單一的/單身的", "3B"), ("double", "雙倍的", "3B"), ("whole", "全部的", "3B"),
    ("half", "一半的", "3B"), ("certain", "確定的", "3B"), ("sure", "確定的", "3B"), ("dead", "死亡的", "3B"), ("alive", "活著的", "3B"), ("very", "非常", "3B"),
    ("too", "太/也", "3B"), ("quite", "相當", "3B"), ("rather", "寧願/相當", "3B"), ("pretty", "相當/漂亮的", "3B"), ("enough", "足夠", "3B"), ("much", "多", "3B"),
    ("more", "更多", "3B"), ("most", "最多", "3B"), ("less", "較少", "3B"), ("least", "最少", "3B"), ("almost", "幾乎", "3B"), ("nearly", "幾乎", "3B"),
    ("hardly", "幾乎不", "3B"), ("really", "真地", "3B"), ("exactly", "確切地", "3B"), ("suddenly", "突然地", "3B"), ("quickly", "快速地", "3B"), ("slowly", "緩慢地", "3B"),
    ("carefully", "小心地", "3B"), ("heavily", "沉重地", "3B"), ("aloud", "大聲地", "3B"), ("maybe", "也許", "3B"), ("perhaps", "或許", "3B"), ("probably", "可能地", "3B"),
    ("surely", "確實地", "3B"), ("certainly", "當然", "3B"), ("indeed", "的確", "3B"), ("always", "總是", "3B"), ("usually", "通常", "3B"), ("often", "經常", "3B"),
    ("sometimes", "有時", "3B"), ("seldom", "很少", "3B"), ("rarely", "罕見地", "3B"), ("never", "從不", "3B"), ("ever", "曾經", "3B"), ("already", "已經", "3B"),
    ("yet", "尚未", "3B"), ("still", "仍然", "3B"), ("just", "剛剛/只是", "3B"), ("then", "那麼/然後", "3B"), ("now", "現在", "3B"), ("soon", "很快地", "3B"),
    ("later", "稍後", "3B"), ("ago", "之前", "3B"), ("before", "在...之前", "3B"), ("after", "在...之後", "3B"), ("while", "當...的時候", "3B"), ("where", "在哪裡", "3B"),
    ("here", "這裡", "3B"), ("there", "那裡", "3B"), ("everywhere", "到處", "3B"), ("nowhere", "無處", "3B"), ("somewhere", "某處", "3B"), ("anywhere", "任何地方", "3B"),
    ("away", "遠離", "3B"), ("out", "外面", "3B"), ("up", "向上", "3B"), ("down", "向下", "3B"), ("over", "在...之上/結束", "3B"), ("under", "在...之下", "3B"),
    ("above", "在...上方", "3B"), ("below", "在...下方", "3B"), ("behind", "在...後面", "3B"), ("beside", "在...旁邊", "3B"), ("near", "附近", "3B"), ("far", "遠的", "3B"),
    ("between", "在(兩者)之間", "3B"), ("among", "在(三者以上)之中", "3B"), ("through", "穿越", "3B"), ("across", "橫越", "3B"), ("around", "周圍", "3B"), ("about", "關於/大約", "3B"),
    ("against", "對抗", "3B"), ("without", "沒有", "3B"), ("within", "在...之內", "3B"), ("into", "進入", "3B"), ("onto", "到...之上", "3B"), ("off", "離開", "3B"),
    ("from", "來自", "3B"), ("by", "藉由/在...旁邊", "3B"), ("with", "和/用", "3B"), ("for", "為了/給", "3B"), ("as", "如同/作為", "3B"), ("than", "比...", "3B"),
    ("because", "因為", "3B"), ("since", "自從/因為", "3B"), ("if", "如果", "3B"), ("unless", "除非", "3B"), ("although", "雖然", "3B"), ("though", "雖然", "3B"),
    ("but", "但是", "3B"), ("or", "或者", "3B"), ("and", "和", "3B"), ("so", "所以", "3B"), ("nor", "也不", "3B"), ("neither", "兩者都不", "3B"),
    ("either", "兩者之一", "3B")
]

full_raw_data = part1_raw_data + part2_raw_data

# 轉換與輸出
word_database_full = [{"en": item[0], "ch": item[1], "level": item[2]} for item in full_raw_data]

def build_full_json():
    print(f"✅ 正在合併處理資料... 總計成功載入 {len(word_database_full)} 個核心單字！")
    try:
        with open('words.json', 'w', encoding='utf-8') as f:
            json.dump(word_database_full, f, ensure_ascii=False, indent=2)
        print("🚀 國中三年 1200 單字『大圓滿終極版』 words.json 製作完成！可以推送到 GitHub 了！")
    except Exception as e:
        print(f"❌ 寫入失敗: {e}")

if __name__ == "__main__":
    build_full_json()